(executable
 (name smoke)
 (modules smoke)
 (libraries solana-types solana-transaction solana-rpc solana-rpc-mirage))

(executable
 (name unikernel)
 (modules unikernel)
 (flags (:standard -w -32-60))
 (libraries
  solana-types
  solana-transaction
  solana-rpc
  solana-rpc-mirage
  http-mirage-client
  lwt))
