(test
 (name test_solana)
 (modules test_solana)
 (package solana)
 (deps
  ../conformance/fixtures/kit-8.0.0-token.json
  ../conformance/fixtures/agave-4.2.1-token.json)
 (libraries
  solana-types
  solana-crypto
  solana-transaction
  solana-rpc
  alcotest
  qcheck-core
  qcheck-alcotest
  yojson
  zarith))

(test
 (name test_rpc_cohttp)
 (modules test_rpc_cohttp)
 (package solana-rpc-cohttp)
 (libraries solana-rpc solana-rpc-cohttp alcotest lwt uri http))
